# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 319198173ad3966530e2f3c63b68f7ce12a453391bfd474a46b6e46a0566e1845826aa7351ec7dea04ec19d6dbac475a918bdb0a4907d4a696bfd8ee808aa11c

test:
  secret_key_base: 0ebd8eaa1c118bfa415857545be783f77b497d7cb6ec9d0e16238608e0ac3c6fd4ad07307f3065b6a4fd275fe718644a7c7211b8e45891c2359e7f7cdd94b72b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
